### ISSUE TITLE
Feature request: save position of form so that it reopens on that position the next time it is opened

### ISSUE THREAD

**Issue by davoutuk** [doonfrs/flutter_floating_dialog#1]
When I drag a 'floating dialog' to a new position on the screen,  is there a way of storing that new position so that when the floating dialog is opened a second time it is displayed in the saved position rather than the default?

Example scenario:
My Flutter web app includes an 'edit xxxx' feature that will display a floating dialog 
The user may wish to drag the floating dialog to a new position in the web app display so that they can see the details on the main display
That drag position should become the new starting position for the 'edit xxxx' floating dialog.

**Comment by doonfrs** [comment]
Thank you for the feedback,
Please update to the latest version ( published to the pub.dev ) to use onDrag callback
* You can use dialogLeft, dialogRight to set the starting position of the dialog.
* Save the value using onDrag callback.
* Make sure not to set autoCenter to true.

I want to keep it simple, the widget will give you the ability to save/load the latest position.
You can use Shared preferences, it is up to you.

```

FloatingDialog(
                  onDrag: (x, y) {
                    print('x: $x, y: $y');
                  },
                  onClose: () {
                    setState(() {
                      _showDialog = false;
                    });
                  },
                  child: const SizedBox(
                      height: 200,
                      width: 300,
                      child: Align(
                          alignment: Alignment.topCenter,
                          child: Text('Dialog Title')))),

```

**Comment by davoutuk** [comment]
The 'onDrag' event handler allows the dragged-to position to be saved,  but how do I set that x/y position into the positioning of the floating dialog the next time it is opened?

**Comment by doonfrs** [comment]
Hi @davoutuk please re-read my reply, I answered you.

> You can use dialogLeft, dialogRight to set the starting position of the dialog.

best;

**Comment by davoutuk** [comment]
Brilliant ! That works really well.
